; ------------------------------------------------------------
; name      Alina
; type      trojan
; cve       —
; year      unknown
; os        Windows
; authors   unknown
; source    RamadhanAmizudin/malware
; archived  RamadhanAmizudin, krisyotam (2026)
; notes     —
; ------------------------------------------------------------
#define HIDDEN_REGISTRY_ENTRY	"HiddenValue"
#define HIDDEN_FILE_NAME		"HiddenFile"
#define HIDDEN_PROCESS_NAME		"HiddenProcess.exe"